### ISSUE TITLE
A global user score is recorded

### ISSUE THREAD

**Issue by mgm-sfrank** [mgm-interns/team-radio#10]
As a user, I want to be rewarded for creating a nice user profile. It's a lot of work!

As a TeamRadio project member, I want to encourage users to create a nice user profile, because it improves the user experience for all other users

*Acceptance criteria*
* In the user profile, I can see the score for my user profile
* The score increases when a profile picture is uploaded - worth about playing 20 songs
* The score does not increase when updating an existing picture

**Comment by baonguyendang** [comment]
Global score (reputation): 
+ How to get point of reputation? You can get point from: 
-	Updating your profile : The first time you update your profile, you can get point.
o	Avatar:  20 points
o	Other: 2 points/ field ( City, country, Bio, first name, last name)

-	Creating your station: For each your station, you can get point 
o	User: Each 10 users who joined your station you get 1 point. Each user is counted one time for the first times join your station.
o	Song: Each 100 songs which was added to your station by another user you get 1 point.
Note: Point which you get from each station will be removed when you delete your station

+ What can you do with your point? 
-	Increase number of your station: After you create your account, you have 1 station in limit. Each 30 points you have you can get 1 station in limit. More point you have more station you can create
Example: After you update full your profile, you can get 30 points and you have 2 stations in limit 

-	Increase your point in station:  When the first times you join each station (not yours) you get a station score. By default as a new user, you have zero. Each 10% your reputation you get 1 station score.
Example: After you update full your profile, you can get 30 points and you have 3 station scores

**Comment by ngyencog** [comment]
In the user profile, I can see the score for my user profile ✔️
The score increases when a profile picture is uploaded - worth about playing 20 songs ✔️
The score does not increase when updating an existing picture ✔️
