### ISSUE TITLE
Sort stations in the switcher by relevance

### ISSUE THREAD

**Issue by mgm-sfrank** [mgm-interns/team-radio#101]
Sort by
* top: new stations with active users
* then active stations with many users
* then active stations with fewer users
* then inactive stations

**Comment by baonguyendang** [comment]
verified #101

**Comment by NguyenTatNhac** [comment]
I have tested it and find some bug:
* Switcher doesn't show number of not logged in user online
* Server emit a lot of redundant events because of "Switcher"
