### ISSUE TITLE
Station's history not work with large list (>90 items)

### ISSUE THREAD

**Issue by pvtri96** [mgm-interns/team-radio#106]
### Expected:
- List will be rendered whether the list has 100 or 1000 

### Possible solutions:
- Virutal List
- Pagination (comming soon)

### TODO:
- [ ] Integrate Virtual List

**Comment by pvtri96** [comment]
Tested & reviewed. There is still no problem with a large list.
Discard #106

**Comment by CodeWinner** [comment]
vifified #106
