### ISSUE TITLE
Can't play the next song if  the song of playing have url as the next song

### ISSUE THREAD

**Issue by CodeWinner** [mgm-interns/team-radio#111]
-Reality  : If now playing and the next song have same url. when now playing is finished then playlist is change but next song is pause

**Comment by baonguyendang** [comment]
Testing is failed

**Comment by pvtri96** [comment]
Bug still happen when dealing with skip song event.

**Comment by pvtri96** [comment]
Tested on my local deployment

**Comment by NguyenTatNhac** [comment]
Tested!

**Comment by hongquy** [comment]
Can play the next song if the song of playing have url as the next song :heavy_check_mark:
