### ISSUE TITLE
Anonymous users can add songs (expected: login is required)

### ISSUE THREAD

**Issue by mgm-sfrank** [mgm-interns/team-radio#113]
How to reproduce:

- if logged in, log out first
- go to any station
- add a song to the playlist

Expected:

- Anonymous users can not add songs to playlists
 
Actual:

- Anonymous users can add songs

**Comment by NguyenTatNhac** [comment]
We have prohibited not logged in users to add songs. But in our discussion of issue #2, users who are not logged in can still create stations. I think that would be embarrassing for the user, because they can create a station but can not add songs later.

**Comment by mgm-sfrank** [comment]
You are right, so we should add at least one more feature so an anonymous user can add songs to his own stations

**Comment by pvtri96** [comment]
Tested.
