### ISSUE TITLE
An anonymous user can add songs to his/her own station

### ISSUE THREAD

**Issue by mgm-sfrank** [mgm-interns/team-radio#121]
As a new user, I want to try out team radio, so I create a station immediately (without registering as a user) - and then I can't add any songs. I feel like being tricked into signing a membership I did not want

*Acceptance criteria*
* after creating a station as an anonymous user, I can add songs to the playlist
* other anonymous users can't add songs
* when I register as a user, the station is assigned to me and appears in the "my stations" list

**Comment by hynguyen2610** [comment]
Hi @mgm-sfrank , with the second requirement, "other anonymous users can't add songs", do you mean that if an anonymous user create a station, it will be a private station, or it still public but no one else can add song to that station?

**Comment by hongquy** [comment]
(1) after creating a station as an anonymous user, I can add songs to the playlist ❌ 
(2) other anonymous users can't add songs ✔️ 
(3) when I register as a user, the station is assigned to me and appears in the "my stations" list ❌ 

Testing:
(1) I can't play a next song (Only the first song added to the station can play)

**Comment by hongquy** [comment]
- After creating a station as an anonymous user, I can add songs to the playlist ✔️ 
- Other anonymous users can't add songs ✔️
- When I register as a user, the station is assigned to me and appears in the "my stations" list ✔️
