### ISSUE TITLE
A user can reset his password

### ISSUE THREAD

**Issue by viethuynh1988** [mgm-interns/team-radio#139]
As an active user, one may forget his account password and want to reset a new password via email notification. 

Acceptance criteria

1. A user clicks on ''forget the password'' and fill his name on the new password recovery window
2. Once a user fills and submits his email, an email will automatically be sent to that email. 
3. A user clicks on the link attached to the email to reset his password.

**Comment by CodeWinner** [comment]
Verified #139

**Comment by pvtri96** [comment]
Tested.
