### ISSUE TITLE
[UX] Lagging when the website and song when switching from playlist tab to history tab

### ISSUE THREAD

**Issue by rocklaam** [mgm-interns/team-radio#142]
*Problem*
When the history is large enough (maybe 20 songs), user switch playlist tab to history tab and the song (is being sung) is lagging. It's just a small UX 💃 
*Solution*
I think you should not save history in DB coninuously, just save it into cookie or sth, when any song roll back, just pull this song into to the top of the list, and history update from cookie ;). When the last person close this link (tab), you save the cookie (history) to the DB ;), good luch ^^! I love this product <3

**Comment by NguyenTatNhac** [comment]
We are fixing it by limit history list, and apply pagination for it!

**Comment by NguyenTatNhac** [comment]
Solution at issue #120

**Comment by CodeWinner** [comment]
Verified #142

**Comment by pvtri96** [comment]
Close #142
