### ISSUE TITLE
Skip songs action is lagged when skipping the next songs after skip now playing

### ISSUE THREAD

**Issue by dungle1811** [mgm-interns/team-radio#146]
**How to produce this bug:**

- Add more than 2 songs.
- Click on dislike button on each song to skip all.

**Expected:**

- The song which is playing will be skipped after 10 seconds and the next songs will be skipped after 5 seconds.

**Actual:**

- Skip now playing: 10s
- Skip the next songs: these songs will be played in 1-2s and disappeared without counting.

**Comment by NguyenTatNhac** [comment]
Reviewed
