### ISSUE TITLE
Song title doesn't change in passive page when playing changed

### ISSUE THREAD

**Issue by NguyenTatNhac** [mgm-interns/team-radio#154]
The title of the song does not change in passive page when now playing is changed.

**Comment by hynguyen2610** [comment]
@NguyenTatNhac , can you please give us a detail reporoducing steps list? Thank you

**Comment by NguyenTatNhac** [comment]
@hynguyen2610 someone has fixed it but doesn't move it to done!

**Comment by hynguyen2610** [comment]
Alright, Was there someone test this? Or we should close this?
