### ISSUE TITLE
User profiles get mixed up after login-with-facebook

### ISSUE THREAD

**Issue by mgm-sfrank** [mgm-interns/team-radio#157]
After I try to login with my facebook user (Steffen Frank), I am logged in as Nadine Gartner

How to reproduce:
- start a freshly installed browser with no caches, history, persistent memory... (Firefox in my case). I have never visited facebook.com in this browser before
- go to facebook.com and verify that no Facebook user account information is stored in the browser (Facebook asks for credentials)
- log in to Facebook with my user Steffen Frank and verify I am actually logged in as Steffen Frank
- go to any website that allows a facebook login (e.g. twoo.com) and verify that my own user account will be used for login
- now go to teamradio.herokuapp.com and login with facebook

Expected result:
- I am logged in as Steffen Frank

Actual result:
- I am logged in as Nadine Gartner

**Comment by hynguyen2610** [comment]
We will have a look, at the moment we still can't find any other similar case. If anyone else meets this problem, please let us know. Thank you.

**Comment by dracudakid** [comment]
i got the same issue ;D

**Comment by mgm-sfrank** [comment]
I tried to test it in the staging environment, but I can't login with facebook

![image](https://user-images.githubusercontent.com/34300548/36092953-bd2f7038-101b-11e8-900b-88d53674e2de.png)

**Comment by hynguyen2610** [comment]
Verified
