### ISSUE TITLE
The application is running on an easy to remember URL

### ISSUE THREAD

**Issue by mgm-sfrank** [mgm-interns/team-radio#16]
As a team radio project member, I want people to easily remember the URL of the application, to increase usage. It must be easy to remember, so people can share the link just by saying it

*Acceptance criteria*
* We find one or more available (and reasonably priced) domain names with a nice top level domain (.org, .fm, .radio, .io...)
* If teamradio domains already exist with the interesting top level domains, discuss changing the name of the application, so it's easier to find a catchy domain name

**Comment by lybaokhanh** [comment]
I think we can name for the project is "[Marconi](https://en.wikipedia.org/wiki/Guglielmo_Marconi)" - the original inventor of the radio. It's easier to find a domain name, and also a respect for this man.

**Comment by minhnb** [comment]
Verified.
New url for team radio: https://www.teamrad.io
