### ISSUE TITLE
Documenting the convention document for frontend code

### ISSUE THREAD

**Issue by hynguyen2610** [mgm-interns/team-radio#163]
The convention for frontend

**Comment by lybaokhanh** [comment]
I think we could try Redux naming convention recommendations like create-react-app v1.1.1 boilerplate:

> The prefix in a reducer to change the state is **apply** (applyCreateReply), in a selector it is **get** (getReply) and in an action creator it is **do** (doCreateReply).

and using bindActionCreators to handle dispatch on mapDispatchToProps.

**Comment by minhnb** [comment]
Documentation:

> https://wiki.mgm-tp.com/confluence/display/TOOLS/Coding+convention
