### ISSUE TITLE
Add QR code (barcode) for station

### ISSUE THREAD

**Issue by hynguyen2610** [mgm-interns/team-radio#173]
As a coffee shop owner, I want to have a QR code to help user access the station with QR scanner in their mobile device.

Acceptance criteria:
- The QR code will appear in the station page.
- The QR code contains the link of the station.

**Comment by hongquy** [comment]
The QR code will appear in the station page. :heavy_check_mark:
The QR code contains the link of the station. :heavy_check_mark:

**Comment by hynguyen2610** [comment]
I closed this
