### ISSUE TITLE
Public project roadmap (functional and technical)

### ISSUE THREAD

**Issue by mgm-sfrank** [mgm-interns/team-radio#186]
As an open source developer, I want to get a quick overview about the projects plans - both about the architectural vision and about the planned future feature set. This allows me to decide, weather or not to join the project and which parts I can contribute.

*Acceptance criteria*
* There is a public place (the github wiki or a public website) with the product roadmap
* the Roadmap contains a description of the planned architecture
* the Roadmap contains a description of future features and possible usage scenarios

**Comment by hongquy** [comment]
- There is a public place (the github wiki or a public website) with the product roadmap :heavy_check_mark:
- the Roadmap contains a description of the planned architecture  :heavy_check_mark:
- the Roadmap contains a description of future features and possible usage scenarios :heavy_check_mark:
