### ISSUE TITLE
The most important pages are mobile friendly

### ISSUE THREAD

**Issue by mgm-sfrank** [mgm-interns/team-radio#187]
As a user with a mobile phone, I want to use TeamRadion in my mobile phone browser to control a stations playlist. I don't need to see the video or hear music, but I want to be able to do anything necessary to participate in managing a playlist.

*Acceptance criteria*
* The most important pages (for mobile use) are mobile friendly:
* On the station page, the main video is disabled. Instead, I can access the playlist features (voting, history, favourites etc.) comfortable on a touch device with a small screen
* When adding songs, I can preview the new song
* I can login with my mobile phone comfortably

**Comment by hongquy** [comment]
- On the station page, the main video is disabled. Instead, I can access the playlist features (voting, -
 history, favourites etc.) comfortable on a touch device with a small screen :heavy_check_mark:
- When adding songs, I can preview the new song :x:
- I can login with my mobile phone comfortably :heavy_check_mark:

Testing:
- When adding song, I can preview the new song. But I cannot add some of songs with long content preview

**Comment by hongquy** [comment]
- On the station page, the main video is disabled. Instead, I can access the playlist features (voting, -
 history, favourites etc.) comfortable on a touch device with a small screen :heavy_check_mark:
- When adding songs, I can preview the new song :heavy_check_mark:
- I can login with my mobile phone comfortably :heavy_check_mark:
