### ISSUE TITLE
The skip rule can be configured per station

### ISSUE THREAD

**Issue by mgm-sfrank** [mgm-interns/team-radio#188]
As the creator of a station, I want to modify the stations rules for skipping songs. With some small, active teams, the 50% downvotes rule works fine. But with bigger teams or more inactive users, skipping should be easier. By configuring the skip rule, I can make TeamRadio interesting for more different usage scenarios.

*Acceptance criteria*
* The station owner can see a settings button on the station page
* Other users don't see this button
* Stations with anonymous owners don't have a settings button
* The button opens a stations settings dialogue, which allows to change the skip rule
* Rule 1 (active by default): skip at 50% downvotes. When this rule is selected, more than 50% of the users must downvote the song
* Rule 2: downvote by owner skips song. When this rule is selected, a single downvote by the station owner will skip the song. Other users up/downvotes only change the song order, but never skip a song

**Comment by hynguyen2610** [comment]
Hi @lybaokhanh , @baonguyendang , @NguyenTatNhac , please consider about creating subtasks for this story if you feel it too big ;)
