### ISSUE TITLE
Technical overview of the future Java backend

### ISSUE THREAD

**Issue by mgm-sfrank** [mgm-interns/team-radio#190]
For the onboarding project, we want to use Java as a backend technology, so the most common mgm technologies are used in this project and developers can get familiar with Java backend concepts

*Acceptance criteria*
* The public backend documentation shows an overview of the future java backend

**Comment by hynguyen2610** [comment]
Hi @dat-ng , could you please make sure that this Technical overview appears in our backend wiki:
https://github.com/mgm-interns/teamradio2-backend/wiki
