### ISSUE TITLE
Technical overview of the future Front End

### ISSUE THREAD

**Issue by mgm-sfrank** [mgm-interns/team-radio#198]
The front end code should follow some architectural and design best practices

Acceptance criteria
*The public frontend documentation shows an overview of the future java backend

**Comment by minhnb** [comment]
https://wiki.mgm-tp.com/confluence/pages/viewpage.action?pageId=121015086

**Comment by hynguyen2610** [comment]
I think we should public the structure in the Wiki (mgm) to make it truely done
