### ISSUE TITLE
Users cannot login to TeamRadio with their Google account

### ISSUE THREAD

**Issue by trinm90** [mgm-interns/team-radio#213]
Platform: Windows
Browser: Chrome

**Step to reproduce:**
1. Access to https://www.teamrad.io/
2. Click button Login
3. Click button Login with Google

**Expected result:**
Users will be redirect to the Google login page & can login with their Google account

**Actual result:**
System show the error 400 redirect_uri_mismatch

**Comment by hynguyen2610** [comment]
We think it is working for now, can you please have a look again, @trinm90 ?
