### ISSUE TITLE
Create the basic structure with Java and Spring

### ISSUE THREAD

**Issue by dat-ng** [mgm-interns/team-radio#223]
Create backend service as Monolith using Java and Spring Framework. 
*The structure should include:*
- *Controllers package* contains public REST APIs
- *Repositories package* the components to connect the database
- *Services package* contains the components to handle logic stuffs
- *Configuration*

**Comment by hynguyen2610** [comment]
This issue was moved to mgm-interns/teamradio2-frontend#14

**Comment by hynguyen2610** [comment]
This issue was moved to mgm-interns/teamradio2-frontend#15
