### ISSUE TITLE
[Hack] Userprofile management 

### ISSUE THREAD

**Issue by dat-ng** [mgm-interns/team-radio#224]
Create the REST APIs to manage user. The user contain id,  full name, date of birth, email, avatar.
As a developer, I want to create, update, delete and get information of user, I also can only update avatar via service. 
*Acceptance Criteria:*
- Using Java, Spring MVC, Mongodb
- Using Spring JPA as persistence
- The email is unique
- The avatar must be uploaded to Cloundinary, and save into database as the url
- All API should do the unit tests

**Comment by hynguyen2610** [comment]
This task will help some new members familize with Java techniques.

**Comment by hynguyen2610** [comment]
For the members who join this task, if you've finished with it, please don't push the code into this repository, you can keep it at your local machine or push it to your own github.
