### ISSUE TITLE
Station Search page is developed seperately

### ISSUE THREAD

**Issue by trinm90** [mgm-interns/team-radio#265]
**Acceptance criteria:**
- In section Station List of Home page, there will be button "See more".
- User will be move to Station Search page when clicking on button "See more".
- Station Search page has a search bar to search for station by name.
- Station Search page also has some filters to filter the stations.
- Station Search page, by default, also has a list of stations order by the number of active users.

**Comment by hynguyen2610** [comment]
Add the moment we have no plan for UI changing, so let's keep the old design until the customers has any other idea ;)
