### ISSUE TITLE
Chat UI is broken in Macbook

### ISSUE THREAD

**Issue by trinm90** [mgm-interns/team-radio#269]
**OS**: Mac
**Browser**: Chrome
**Version**: v0.1.1

**Step to reproduce**:
1. Access teamrad.io
2. Click on a station
3. Observe the chat box

**Expected result**:
The chat box is in the right side of the song list.

**Actual result**:
The chat box is broken & displayed below the song list & player.

**Comment by dungle1811** [comment]
Hi @trinm90 and @mgm-sfrank , I've checked this problem on another MacBooks and it seems to be ok and I didn't see your problem, the chatbox is still full width. I think maybe your MacBook is cached and it is not updated to the latest version yet. Have you ever restart your Chrome browser (by pressing Ctrl + F5)? If not, please do that and respond to me if this happens again. Thanks.

**Comment by trinm90** [comment]
I also tried "Device toolbar" of Chrome to test in different screen resolutions. But everything seems to be just fine.
