### ISSUE TITLE
I can register as a user

### ISSUE THREAD

**Issue by mgm-sfrank** [mgm-interns/team-radio#5]
As a user of TeamRadio, I want to register and give myself a user name, so people can see which songs are added by me. People should know what kind of music I like.

*Acceptance criteria*
* On the TeamRadio home page and on each station page, there is a way to register as a new user
* During registration, I can register with a unique user name and set my password
* After registration, I am automatically logged in
* I can also login (from any station page) with my user name and a password
* In the playlist, my user name is shown for each of my playlist entries

**Comment by ezellbuoee** [comment]
"In the playlist, my user name is shown for each of my playlist entries", this feature is not yet implemented and i will like to the user avatar instead of just username, and when i hover on the avatar i want to see the username

Note : Clicking on the user avatar can lead to user profile page

**Comment by ezellbuoee** [comment]
Error message should not be synchronize among pages
Error message should be cleared when end users navigate from login to register and register to login.
