### ISSUE TITLE
I can mark songs as favourite

### ISSUE THREAD

**Issue by k2pctdn** [mgm-interns/team-radio#63]
Each song in every station should have "Favourite" option. As each song can be played just one time and then it disappears. When users find a song that is interesting for them, they should be able to save the song in a private favourite list. No need to Shazam; no need to open Youtube, search for the song then add to their own playlists; just click one button and get back to work.

**Comment by CodeWinner** [comment]
Verified

**Comment by pvtri96** [comment]
Tested!
