### ISSUE TITLE
Redesign up vote & down vote buttons

### ISSUE THREAD

**Issue by pvtri96** [mgm-interns/team-radio#69]
The current Up & Down icon in playlist video made the users feel wrong about the meaning up & down vote feature. So that, we need to rework these buttons to make it less confusing.

Acceptance criteria:
- [x] The upvote & downvote will be more like Youtube.
- [x] Up & down vote score will be displayed separately.

**Comment by pvtri96** [comment]
### New up & down vote button showcase
![image](https://user-images.githubusercontent.com/28696888/35034382-8d6e6b04-fba0-11e7-8177-f6b91c5af629.png)

**Comment by NguyenTatNhac** [comment]
Tested!!!
