### ISSUE TITLE
Videos does work properly on mobile app

### ISSUE THREAD

**Issue by ezellbuoee** [mgm-interns/team-radio#76]
Steps to reproduce:

1. create a channel from a pc or your mobile phone
2. access the channel from mobile browser, in my case Chrome and UC web browser

Expected result :
Music from the channel should be properly played without user ability to change the seconds or minute of the video

Actual result:
UC Web : user is able to change the seconds or minute of the video
Chrome :  music refused to play or preview when links are being added

Note :  Chrome is of higher priority

**Comment by trinm90** [comment]
We will have a new mobile UI without the YouTube player. Therefore, we don't have to investigate this issue anymore.
