### ISSUE TITLE
The skip-treshold decreases with playing time

### ISSUE THREAD

**Issue by mgm-sfrank** [mgm-interns/team-radio#87]
My playlist sometimes gets stuck because somebody posted a really long video or the video can't be played because of location/copyright issues. When the current listeners are inactive and don't downvote the song quickly, I have to change stations. I want a way to make skipping easier in annoying situations

*Acceptance criteria*
* With each full minute playing, it needs one less downvote to skip a song. Example: a song is skipped after 5 downvotes. After 2 minutes playtime, it only needs 3 minutes
* When a song is playing and already has some downvotes, the skip threshold eventually decreases below the number of current downvotes. In this case, the song is not skipped - only if a user actively clicks downvote again, the song is skipped

**Comment by NguyenTatNhac** [comment]
I think I need to explain to you a bit about the rule of skipping the song: 
Songs will only be skipped when there is **more than 50% agreement** from people who are **online on the station** and **logged in**. And we will **not count the downvotes of those who have left the station**. So I think it would be okay if a song already had a few downvotes.
