### ISSUE TITLE
Users can only listen to one station at a time

### ISSUE THREAD

**Issue by mgm-sfrank** [mgm-interns/team-radio#89]
A logged-in user can open TeamRadio in different browser tabs and be active in different stations at the same time without actually listening to all of these stations. In this way, a user can gain unwarranted voting rights, increase the skip threshold and disrupt other users' stations

*Acceptance criteria*
* Logged-in users can only listen to one station at a time
* When a user opens TeamRadio several times (in different browsers, different tabs, from different devices), the usr is assigned to the most recent station
* The user does not have more voting rights and does not increase the skip threshold by opening TeamRadio more than once

**Comment by CodeWinner** [comment]
Bug : 
- Open more than 2 tabs
- Pick a other station
- When icon circular process is going.
- Pick a other station
- Push very many notification

**Comment by pvtri96** [comment]
We have an infinite loop while 2 tabs dispatch and receive 1 action so many time.
I will take care of that.
