### ISSUE TITLE
Each station has a page for passive users

### ISSUE THREAD

**Issue by mgm-sfrank** [mgm-interns/team-radio#9]
As a passive user, I only want to listen to music, but not add any songs myself. I don't need all the input fields and links and stuff. Instead, I want a beautiful "now playing" page with no interactive elements. I want to show this page fullscreen on a big monitor in my team room.

*Acceptance criteria*
* on every TeamRadio station page, there is a link to the station's "now playing" page
* on the "now playing" page, the TeamRadio logo is shown, together with information on the current song and the user who added it (if it is a registered user)
* The song is played just like on the TeamRadio station page, but no songs can be added
* The page looks really nice

**Comment by dungle1811** [comment]
For passive users, if they just want to listen to music without interaction, I think the simple solution is let them stay on the station page and when they click on a `light` icon, there is just a video which is playing and users cannot interact with any elements, except some action buttons of a player like `volume`, `share`. Also, they just click on the `light` icon again to back to the initial status of the page.

**Comment by NguyenTatNhac** [comment]
Passive users's page not responsive in my laptop screen (1366*768).
I can only see half of the video frame and cannot scroll down to see full
